# Generated by Django 2.1.5 on 2019-02-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_scheduler_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduler',
            options={},
        ),
    ]
